namespace: ernstov
blank-6886:
  defines: runnable
  containers:
    blank-6886:
      build: .
  variables:
    password:
      env: ADMIN_PASSWORD
      type: string
      value: not-set
    user:
      env: ADMIN_USERNAME
      type: string
      value: admin
  services:
    webserver:
      container: blank-6886
      port: 8080
      protocol: tcp
